name: build-publish

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses:  totaldebug/sphinx-publish-action@1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        sphinx_src: "source"
        target_path: "docs"
        target_branch: "main"
        cname: blog.smidgebit.com
