name: build-publish

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9.x"
    - name: build
      run: |
        pip install -r source/requirements.txt
        make html
    - name: publish
      env:
        GIT_COMMITTER_NAME: $GITHUB_ACTOR
        GIT_COMMITTER_EMAIL: "<>"
      run: |
        ghp-import -n -c blog.smidgebit.com -m "publish spinx html to gh-pages" -p -o
